export const SET_THEME = 'setTheme'
export const SET_MENUS_ACTIVE = 'setMenusActive'
export const SET_MENUS_INIT_RENDER = 'setMenusInitRender'
export const SET_MENUS_INIT = 'setMenusInit'
export const SET_MENUS_CLOSE_ALL = 'setMenusCloseAll'
export const SET_NOW_ACTIVE = 'setNowActive'
export const SET_DEMO_ROUTE = 'setRouteList'
