<template>
  <section>
    <h2>table</h2>
    <table>
      <thead>
        <tr>
          <th>表头1</th>
          <th>表头2</th>
          <th>表头3</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>4</td>
          <td>5</td>
          <td>6</td>
        </tr>
        <tr>
          <td>7</td>
          <td>8</td>
          <td>9</td>
        </tr>
        <tr>
          <td>10</td>
          <td>11</td>
          <td>12</td>
        </tr>
      </tbody>
    </table>
  </section>
</template>
<script setup>
defineOptions({ name: 'view-demo-filmstrip-section24' })
</script>
