version: '1.0'
name: build
displayName: build
triggers:
  trigger: manual
stages:
  - name: stage-efc25181
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 执行编译命令'
          - npm install --legacy-peer-deps && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_nodejs
      - step: release@gitee
        name: release_gitee
        displayName: Gitee Release
        releaseName: build-dist
        description: build-dist
        tagName: build-dist
        upstreamArtifact:
          - BUILD_ARTIFACT
        assertFiles: null
        prerelease: false
        allowUpdate: true
        notify: []
        strategy:
          retry: '0'
        dependsOn: publish_general_artifacts
